=== VolhaHurynovich/JavaTasks/XML_XSD/XSD_1.xsd
<?xml version="1.0" encoding="UTF-8"?>
        <xsd:schema
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                targetNamespace="http://www.epam.example.org/Library"
                xmlns:tns="http://www.epam.example.org/Library"
                elementFormDefault="qualified">
            <xsd:element name="Library" type="tns:MyLibrary"/>
            <xsd:complexType name="MyLibrary">
                <xsd:sequence>
                    <xsd:element name="Book" type="tns:Book" minOccurs="0" maxOccurs="unbounded"/>
                    <xsd:element name="LibraryName" type="xsd:string"/>
                </xsd:sequence>
            </xsd:complexType>

            <xsd:complexType name="Book">
                <xsd:sequence>
                    <xsd:element name="Genre" type="tns:Genre"/>
                    <xsd:element name="Title" type="xsd:string"/>
                    <xsd:element name="Author" minOccurs="1" maxOccurs="unbounded">
                        <xsd:complexType>
                            <xsd:sequence>
                                <xsd:element name="FirstName" type="xsd:string"/>
                                <xsd:element name="LastName" type="xsd:string"/>
                            </xsd:sequence>
                        </xsd:complexType>
                    </xsd:element>
                    <xsd:element name="CountPage" type="xsd:positiveInteger"/>
                    <xsd:element name="YearCreate" type="xsd:gYear"/>
                    <xsd:element name="Country" type="tns:Country"/>
                </xsd:sequence>
                <xsd:attribute name="ID" type="xsd:positiveInteger"/>
            </xsd:complexType>

    <xsd:simpleType name="Genre">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="Comedy"/>
            <xsd:enumeration value="Fantasy"/>
            <xsd:enumeration value="Non-fiction"/>
            <xsd:enumeration value="Satire"/>
            <xsd:enumeration value="Tragedy"/>
            <xsd:enumeration value="Horror"/>
            <xsd:enumeration value="Tragicomedy"/>
            <xsd:enumeration value="Novel"/>
            <xsd:enumeration value="Without category"/>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="Country">
        <xsd:restriction
            base="xsd:string">
            <xsd:pattern value="[a-zA-Z]+"/>
        </xsd:restriction>
    </xsd:simpleType>
</xsd:schema>

=== VolhaHurynovich/JavaTasks/XML_XSD/XML_1.xml
<?xml version="1.0" encoding="UTF-8"?>
<lib:Library xmlns:lib="http://www.epam.example.org/Library"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://www.epam.example.org/Library XSD_1.xsd">
    <lib:Book ID="201">
        <lib:Genre>Novel</lib:Genre>
        <lib:Title>Gone with the Wind</lib:Title>
        <lib:Author>
            <lib:FirstName>Margaret</lib:FirstName>
            <lib:LastName>Mitchell</lib:LastName>
        </lib:Author>
        <lib:CountPage>854</lib:CountPage>
        <lib:YearCreate>1936</lib:YearCreate>
        <lib:Country>USA</lib:Country>
    </lib:Book>
    <lib:Book ID="203">
        <lib:Genre>Novel</lib:Genre>
        <lib:Title>War and Peace</lib:Title>
        <lib:Author>
            <lib:FirstName>Leo</lib:FirstName>
            <lib:LastName>Tolstoy</lib:LastName>
        </lib:Author>
        <lib:CountPage>854</lib:CountPage>
        <lib:YearCreate>1869</lib:YearCreate>
        <lib:Country>Russia</lib:Country>
    </lib:Book>
    <lib:LibraryName>National Library</lib:LibraryName>
</lib:Library>
